package sensetime.senseme.com.effects

/**
 * @author lsy
 * @date   2020-01-02
 */
class ListHelper {


    companion object {

        fun getMakeList(): ArrayList<TestBean> {
            val list = java.util.ArrayList<TestBean>();
            list.add(TestBean("原图",
                    arrayListOf<Float>(
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f), false))
//            list.add(TestBean("初恋脸",
//                    arrayListOf<Float>(
//                            0.0f,
//                            0.0f,
//                            0.69f,
//                            0.0f,
//                            0.54f,
//                            0.0f,
//                            0.18f,
//                            1.0f,
//                            1.0f,
//                            0.0f,
//                            -0.53f,
//                            0.0f,
//                            0.36f,
//                            0.0f,
//                            1.0f,
//                            0.0f,
//                            0.0f,
//                            0.0f), true));
            list.add(TestBean("幼幼脸",
                    arrayListOf<Float>(
                            0.0f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.35f,
                            0.0f,
                            -0.87f,
                            1.0f,
                            1.0f,
                            0.0f,
                            -0.76f,
                            0.59f,
                            1.0f,
                            0.0f,
                            0.72f,
                            0.0f,
                            0.0f,
                            1.0f), false))
//            list.add(TestBean("幼幼脸",
//                    arrayListOf<Float>(
//                            0.15f,
//                            0.10f,
//                            0.0f,
//                            0.36f,
//                            0.35f,
//                            0.20f,
//                            0.20f,
//                            0.0f,
//                            1.0f,
//                            0.12f,
//                            0.67f,
//                            -0.42f,
//                            0.12f,
//                            0.0f,
//                            0.0f,
//                            0.35f,
//                            1.0f,
//                            1.0f), false))
            list.add(TestBean("网红脸",
                    arrayListOf<Float>(
                            0.50f,
                            0.53f,
                            0.92f,
                            0.20f,
                            0.29f,
                            0.27f,
                            -0.15f,
                            0.12f,
                            1.0f,
                            0.35f,
                            -0.36f,
                            0.33f,
                            0.37f,
                            0.0f,
                            0.31f,
                            1.0f,
                            1.0f,
                            1.0f), false))
//            list.add(TestBean("性感甜美脸",
//                    arrayListOf<Float>(
//                            0.0f,
//                            0.0f,
//                            0.30f,
//                            0.0f,
//                            0.0f,
//                            0.0f,
//                            -1.0f,
//                            -0.56f,
//                            0.0f,
//                            0.0f,
//                            1.0f,
//                            -0.5f,
//                            1.0f,
//                            0.0f,
//                            -1.0f,
//                            0.83f,
//                            0.0f,
//                            0.0f), false))
            list.add(TestBean("日系脸",
                    arrayListOf<Float>(
                            0.0f,
                            0.0f,
                            0.64f,
                            0.0f,
                            0.13f,
                            0.0f,
                            -0.59f,
                            0.46f,
                            1.0f,
                            0.0f,
                            0.0f,
                            0.69f,
                            0.51f,
                            0.0f,
                            1.0f,
                            0.0f,
                            0.0f,
                            0.49f), false))
//            list.add(TestBean("古典脸",
//                    arrayListOf<Float>(
//                            0.0f,
//                            0.31f,
//                            0.58f,
//                            0.0f,
//                            0.14f,
//                            0.0f,
//                            -0.51f,
//                            -1.00f,
//                            1.0f,
//                            0.0f,
//                            0.0f,
//                            0.0f,
//                            0.68f,
//                            0.0f,
//                            0.0f,
//                            0.0f,
//                            1.0f,
//                            1.0f), false))
            list.add(TestBean("变年轻",
                    arrayListOf<Float>(
                            0.0f,
                            0.27f,
                            0.13f,
                            0.0f,
                            0.0f,
                            0.0f,
                            0.15f,
                            0.0f,
                            1.0f,
                            0.13f,
                            -0.03f,
                            0.61f,
                            1.0f,
                            0.56f,
                            0.36f,
                            0.0f,
                            1.0f,
                            1.0f), false))
            list.add(TestBean("初恋脸",
                    arrayListOf<Float>(
                            0.0f,
                            0.28f,
                            0.33f,
                            0.0f,
                            0.33f,
                            -0.50f,
                            -0.25f,
                            0.58f,
                            1.0f,
                            0.0f,
                            -0.40f,
                            -0.30f,
                            0.48f,
                            0.42f,
                            0.45f,
                            0.0f,
                            0.55f,
                            0.60f), false))
//            list.add(TestBean("初恋脸男",
//                    arrayListOf<Float>(
//                            0.0f,
//                            0.54f,
//                            0.44f,
//                            0.0f,
//                            0.10f,
//                            -0.50f,
//                            0.0f,
//                            0.64f,
//                            0.45f,
//                            0.12f,
//                            0.0f,
//                            0.0f,
//                            0.0f,
//                            0.39f,
//                            0.0f,
//                            0.23f,
//                            0.20f,
//                            0.40f), false))
            return list;
        }


    }
}