name: gengmei_app_face
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  flutter_swiper: ^1.0.6
  extended_image: ^0.6.8
  toast: ^0.1.4
#  gengmei_flutter_plugin:
#    git:
#      url: 'git@git.wanmeizhensuo.com:linshengyu/flutter_plugin.git'
#      ref: "d37dd26d78c3ce0ae288ec69acc2b244307e2752"
#  flutter_common:
#    git:
#      url: 'git@git.wanmeizhensuo.com:linshengyu/GM_flutter_plugin_common.git'
#      ref: '03db60fcdb10e1ce9a8e7c5f52bb52e64e87749f'
  flutter_album:
    git:
      url: 'https://github.com/asd451398533/flutter_album.git'
      ref: 'b8c738bf56de050ed42557aece2c8d22cbad218e'
  flutter_common:
    git:
      url: 'https://github.com/asd451398533/flutter_common.git'
      ref: '0abdb58403883249ccd556b4f0cdeaaf6e9a3d76'
  gengmei_flutter_plugin:
    git:
      url: '/Users/apple/lsy/gengmei_flutter_plugin'

dev_dependencies:
  source_gen: '>=0.8.0'
  build_runner: ^1.6.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/